sudo: false
language: go

services:
    - docker

env:
    global:
        - REDIS_VERSION=alpine

go:
    - 1.8
    - tip

before_install:
    - docker run -d -p 6379:6379 "redis:$REDIS_VERSION"

install:
    - go get github.com/stretchr/testify/require

script:
    - go test -v-race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
